networks:
  harisato:
    path: /Users/lvh/akachain/akc-admin-go/configs/networks/connection-harisato.yaml
  huanlv:
    path: /Users/lvh/akachain/akc-admin-go/configs/networks/connection-huanlv.yaml
contexts:
  harisato:
    network: harisato
    organization: harisato
    user: admin-harisato
    channel: akcchannel
    orderers:
    - orderer0-orderer.harisato
    peers:
    - peer0-harisato.harisato
    - peer1-harisato.harisato
  huanlv:
    network: huanlv
    organization: huanlv
    user: admin-huanlv
    channel: akcchannel
    orderers:
      - orderer0-orderer.harisato
    peers:
      - peer0-huanlv.huanlv
      - peer1-huanlv.huanlv
current-context: harisato
